# Generated by Django 3.2.7 on 2022-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220424_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
